In [19]:
import json
from pathlib import Path
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
import os

import dspy

In [2]:
from loguru import logger

logger.remove()
logger.add(lambda _: None, level="CRITICAL")

1

In [3]:
lm = dspy.LM(
    "hosted_vllm/ibm-granite/granite-4.1-8b",
    api_base="http://boris:30000/v1",
    cache=False,
)
dspy.configure(lm=lm)

In [4]:
def load_jsonl(
    path: str | Path,
    *,
    input_keys: tuple[str, ...] = ("question", "reference_datetime"),
) -> list[dspy.Example]:
    examples = []

    with Path(path).open(encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            try:
                row = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(
                    f"Invalid JSON in {path}, line {line_number}"
                ) from error

            example = dspy.Example(**row).with_inputs(*input_keys)
            examples.append(example)

    return examples

# EDA

In [5]:
trainset = load_jsonl("../data/train.jsonl")
valset = load_jsonl("../data/validation.jsonl")

In [6]:
print(trainset[0])

Example({'id': 'train-001', 'family_id': 'train-now-001', 'scenario': 'schedule_now_alias', 'question': 'Next Caltrain from Sunnyvale to SF?', 'reference_datetime': '2026-08-24T15:00:00-07:00', 'is_schedule_question': True, 'departure_station': 'sunnyvale', 'arrival_station': 'san francisco', 'departure_time': '2026-08-24T15:00:00-07:00', 'time_tolerance_minutes': 5}) (input_keys={'reference_datetime', 'question'})

In [7]:
print(len(trainset))
print(len(valset))

88
91

In [8]:
from caltrain_bot.question_analysis import (
    CaltrainScheduleHelper,
    build_station_extraction_signature,
    datetime_calculator,
    QuestionsClassifier,
    UnsupportedQuestion,
    ScheduleQuestion,
)

In [9]:
stations = (
    "22nd street",
    "bayshore",
    "belmont",
    "blossom hill",
    "broadway",
    "burlingame",
    "california avenue",
    "capitol",
    "college park",
    "gilroy",
    "hayward park",
    "hillsdale",
    "lawrence",
    "menlo park",
    "millbrae",
    "morgan hill",
    "mountain view",
    "palo alto",
    "redwood city",
    "san antonio",
    "san bruno",
    "san carlos",
    "san francisco",
    "san jose diridon",
    "san martin",
    "san mateo",
    "santa clara",
    "south san francisco",
    "sunnyvale",
    "tamien",
)

In [10]:
prog = CaltrainScheduleHelper(
    question_classifier=dspy.Predict(QuestionsClassifier),
    stations_departure_time_extractor=dspy.ReAct(
        signature=build_station_extraction_signature(stations),
        tools=[datetime_calculator],
        max_iters=10,
    ),
    stations=stations,
)

In [11]:
prog(
    question="caltrain from sf to palo alto",
    reference_datetime=datetime.now(ZoneInfo("America/Los_Angeles")).isoformat(),
)

ScheduleQuestion(departure_station='san francisco', arrival_station='palo alto', departure_time=datetime.datetime(2026, 8, 25, 10, 6, 23, 673437, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))))

In [20]:
from dspy.teleprompt import GEPA
from dspy.teleprompt.gepa.gepa_utils import DSPyTrace

# Baseline

In [23]:
FIELD_REWARD = 1.0 / 3.0


def parse_datetime(value: object) -> datetime | None:
    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(
                value.removesuffix("Z") + ("+00:00" if value.endswith("Z") else "")
            )
        except ValueError:
            return None
    else:
        return None

    return parsed if parsed.utcoffset() is not None else None


def stations_match(expected: object, predicted: object) -> bool:
    def normalize(value: object) -> str | None:
        if not isinstance(value, str):
            return None
        return " ".join(value.casefold().split()) or None

    expected = normalize(expected)
    predicted = normalize(predicted)

    return expected is not None and predicted == expected


def times_match(
    expected: object,
    predicted: object,
    tolerance_minutes: float,
) -> bool:
    expected_time = parse_datetime(expected)
    predicted_time = parse_datetime(predicted)

    if expected_time is None or predicted_time is None:
        return False

    tolerance = timedelta(minutes=tolerance_minutes)
    return abs(predicted_time - expected_time) <= tolerance


def baseline_metric(
    gold: dspy.Example,
    pred: ScheduleQuestion | UnsupportedQuestion,
    trace: DSPyTrace | None = None,
    pred_name: str | None = None,
    pred_trace: DSPyTrace | None = None,
) -> float:
    if not gold.is_schedule_question:
        return float(isinstance(pred, UnsupportedQuestion))

    if not isinstance(pred, ScheduleQuestion):
        return 0.0

    field_results = (
        stations_match(gold.departure_station, pred.departure_station),
        stations_match(gold.arrival_station, pred.arrival_station),
        times_match(
            gold.departure_time,
            pred.departure_time,
            gold.time_tolerance_minutes,
        ),
    )

    if all(field_results):
        return 1.0

    reward = 0.0
    for is_correct in field_results:
        if is_correct:
            reward += FIELD_REWARD

    return reward

In [13]:
evaluator = dspy.Evaluate(
    devset=trainset + valset,
    num_threads=2,
    display_progress=True,
    display_table=5,
    provide_traceback=False,
    max_errors=5,
    failure_score=0.0,
)

In [14]:
merged_set_result = evaluator(prog, metric=baseline_metric)

Average Metric: 112.00 / 179 (62.6%): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [14:49<00:00,  4.97s/it]

2026/08/25 10:21:18 INFO dspy.evaluate.evaluate: Average Metric: 112.00000000000003 / 179 (62.6%)

,id,family_id,scenario,question,reference_datetime,is_schedule_question,departure_station,arrival_station,departure_time,time_tolerance_minutes,prediction,baseline_metric
0,train-001,train-now-001,schedule_now_alias,Next Caltrain from Sunnyvale to SF?,2026-08-24T15:00:00-07:00,True,sunnyvale,san francisco,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='sunnyvale', arrival_station='s...",✔️ [0.667]
1,train-002,train-now-002,schedule_now_reversed_alias,I need to get to 4th and King from Palo Alto. What's the next one?,2026-08-24T15:00:00-07:00,True,palo alto,san francisco,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='palo alto', arrival_station='m...",✔️ [0.667]
2,train-003,train-now-003,schedule_now_alias,Catching the next train at Diridon going to Mountain View.,2026-08-24T15:00:00-07:00,True,san jose diridon,mountain view,2026-08-24T15:00:00-07:00,5.0,UnsupportedQuestion(),✔️ [0.000]
3,train-004,train-now-004,schedule_now,Any train leaving Redwood City for Millbrae right now?,2026-08-24T15:00:00-07:00,True,redwood city,millbrae,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='redwood city', arrival_station...",✔️ [0.333]
4,train-005,train-now-005,schedule_now_alias,"ASAP, 22nd St to San Mateo - what can I catch?",2026-08-24T15:00:00-07:00,True,22nd street,san mateo,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='22nd street', arrival_station=...",✔️ [0.667]

In [15]:
merged_set_result.score

62.57

# Optimizer

In [24]:
prompt_lm = dspy.LM(
    model="openrouter/moonshotai/kimi-k3",
    api_base="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)

In [27]:
prompt_lm("Hello!")

[{'text': 'Hello! How can I help you today?',
  'reasoning_content': 'The user has simply said "Hello!" - a friendly greeting. This is about as simple as messages get. There\'s no complex question, no task, no problem to solve. Just a greeting.\n\nWhat\'s the appropriate response here? A warm, friendly greeting back. I shouldn\'t overload them with information or ask a bunch of questions. Just a natural, warm hello and maybe an invitation to share what they\'d like help with.\n\nFormat considerations: This should be very short. A greeting deserves a greeting back - maybe one or two sentences. No headers, no bullet points, no lengthy explanation of what I can do. Just a natural conversational response. Something like "Hello! How can I help you today?" or a variation that feels warm and natural.\n\nI could be slightly more personable than the robotic "How may I assist you?" - something friendly and open.'}]

In [ ]:
gepa_optimizer = GEPA(metric=baseline_metric, reflection_lm=prompt_lm, auto="medium")
gepa_prog = gepa_optimizer.compile(student=prog, trainset=trainset, valset=valset)

In [35]:
gepa_prog.save("../data/prog_caltrain_schedule_helper_gepa_medium", save_program=True)

2026/08/25 15:51:58 WARNING dspy.primitives.base_module: Loading untrusted .pkl files can run arbitrary code, which may be dangerous. To avoid this, prefer saving using json format using module.save("module.json").

In [52]:
gepa_prog._question_classifier

Predict(StringSignature(question -> is_schedule_question
    instructions='Classify whether a question contains a self-contained Caltrain schedule lookup.\n\nA supported question identifies both departure and arrival stations. A departure\ntime is optional. Reject questions that omit either station or depend on prior\nconversational context.'
    question = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Question:', 'desc': '${question}'})
    is_schedule_question = Field(annotation=bool required=True json_schema_extra={'desc': 'True only when both departure and arrival stations can be resolved from this question; the departure time may be omitted', '__dspy_field_type': 'output', 'prefix': 'Is Schedule Question:'})
))

In [53]:
gepa_prog._stations_departure_time_extractor

react = Predict(StringSignature(question, reference_datetime, trajectory -> next_thought, next_tool_name, next_tool_args
    instructions='Extract a Caltrain route and an optional departure time. Return null for a station that cannot be resolved from the question. Return null for the departure time when the question does not specify one.\n\nYou are an Agent. In each episode, you will be given the fields `question`, `reference_datetime` as input. And you can see your past trajectory so far.\nYour goal is to use one or more of the supplied tools to collect any necessary information for producing `departure_station`, `arrival_station`, `departure_time`.\n\nTo do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.\nAfter each tool call, you receive a resulting observation, which gets appended to your trajectory.\n\nWhen writing next_thought, you may reason about the current situation and plan for future steps.\nWhen selecting the next_tool_name and its next_tool_args, the tool must be one of:\n\n(1) datetime_calculator, whose description is <desc>Calculate a new datetime by adding minutes (including negative values) to a given start time.</desc>. It takes arguments {\'start_time\': {\'type\': \'string\'}, \'delta_minutes\': {\'type\': \'integer\'}}.\n(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `departure_station`, `arrival_station`, `departure_time`, are now available to be extracted.</desc>. It takes arguments {}.\nWhen providing `next_tool_args`, the value inside the field must be in JSON format.\n\n## Output semantics\n- `departure_station`, `arrival_station`: canonical Caltrain station names (see list below). Return null for either one if the question does not name it or names a place that is not a Caltrain station.\n- `departure_time`: a full ISO 8601 datetime string that combines the resolved calendar date, the resolved 24-hour clock time, and the UTC offset copied from `reference_datetime` (e.g. `2026-08-24T19:30:00-07:00`). Return null when the question does not specify a departure time. There is no timetable/schedule tool, so never invent or look up "real" train times; the departure time is the time the user states or implies.\n\n## Caltrain domain knowledge\nCaltrain runs between San Francisco and Gilroy along the Peninsula. Stations, north to south (common aliases in parentheses):\nSan Francisco (a.k.a. "SF", "the city", "4th & King" / "4th and King"), 22nd Street, Bayshore, South San Francisco, San Bruno, Millbrae (BART/SFO transfer), Broadway, Burlingame, San Mateo, Hayward Park, Hillsdale, Belmont, San Carlos, Redwood City, Atherton, Menlo Park, Palo Alto, Stanford (special-event service only), California Avenue (a.k.a. "California Ave", "Cal Ave"), San Antonio, Mountain View, Sunnyvale, Lawrence, Santa Clara, College Park, San Jose Diridon (a.k.a. "Diridon", "San Jose"), Tamien, Capitol, Blossom Hill, Morgan Hill, San Martin, Gilroy.\n\nNotes:\n- Stations south of Tamien (Capitol, Blossom Hill, Morgan Hill, San Martin, Gilroy) are served only during weekday commute peaks, and Atherton/Broadway/College Park/Stanford have limited or event-only service — they are still valid station names for extraction.\n- Normalize aliases to the canonical name: "Diridon"/"San Jose" -> "San Jose Diridon"; "SF"/"the city"/"4th and King" -> "San Francisco"; "Cal Ave" -> "California Avenue".\n- NOT Caltrain stations (return null if one is requested): Oakland, Berkeley, Fremont, Sacramento, SFO airport itself, Santa Clara–Great America / Levi\'s Stadium (served by ACE/Capitol Corridor, not Caltrain), and any BART-only city.\n\n## Resolving departure_time\nAnchor everything to `reference_datetime` (its calendar date and its UTC offset).\n1. Relative day words: "today"/"tonight" -> same date as reference_datetime; "tomorrow" -> +1 day (1440 minutes); "day after tomorrow" -> +2 days; a weekday name -> the next occurrence of that weekday on/after the reference date.\n2. Clock times: convert to 24-hour time. An explicit AM/PM wins. Otherwise use daypart/context cues in the question: "morning", "breakfast", "commute in" -> AM; "afternoon", "evening", "tonight", "night", "after lunch", "after dinner", "heading home" -> PM. "noon"/"midday" -> 12:00; "midnight" -> 00:00. Handle verbal forms too ("half past seven" -> :30, "quarter to eight" -> 7:45).\n3. "in N minutes/hours" or "N minutes from now" -> add N minutes to reference_datetime.\n4. Assemble the final ISO string: resolved date + resolved 24h time + the offset from reference_datetime.\n5. Whenever a day shift or a time-of-day change is involved, verify the arithmetic with datetime_calculator before finishing: set start_time = reference_datetime and delta_minutes = (target minus reference). Worked deltas for reference 2026-08-24T15:00:00-07:00:\n   - "7:30 tonight" (19:30 same day): delta_minutes = 270 -> 2026-08-24T19:30:00-07:00\n   - "tomorrow 6:40 AM": delta_minutes = 940 -> 2026-08-25T06:40:00-07:00\n   The tool handles midnight/month/year rollover for you. Do NOT call finish while the departure date or AM/PM is still unresolved — an unanchored or AM/PM-confused time is the most common failure.\n6. If the question states no departure time at all, output departure_time = null; do not estimate one from typical schedules.\n\n## Per-episode checklist\n1. Parse the two stations from the question; map aliases; return null for any station that cannot be resolved.\n2. Locate the time expression (if any); resolve the relative day and the AM/PM from context; compute the absolute ISO datetime, verifying with datetime_calculator when the day or hour changes relative to reference_datetime.\n3. In your final next_thought, explicitly state all three values: departure_station, arrival_station, and departure_time (full ISO 8601 with offset, or null). Only then call finish.\n\n## Worked examples\nA) question: "Leaving Menlo Park for 22nd Street after dinner, say 7:30 tonight." reference_datetime: 2026-08-24T15:00:00-07:00\n- next_thought: Menlo Park and 22nd Street are both valid Caltrain stations. "Tonight" = same date as reference (2026-08-24); "after dinner" implies PM, so 7:30 -> 19:30. That is 270 minutes after 15:00; verify with the tool.\n- next_tool_name: datetime_calculator\n- next_tool_args: {"start_time": "2026-08-24T15:00:00-07:00", "delta_minutes": 270}\n- (observation: 2026-08-24T19:30:00-07:00)\n- next_thought: departure_station = Menlo Park, arrival_station = 22nd Street, departure_time = 2026-08-24T19:30:00-07:00. All fields resolved.\n- next_tool_name: finish\n- next_tool_args: {}\n\nB) question: "Tomorrow at 6:40 AM, Gilroy to San Jose Diridon." reference_datetime: 2026-08-24T15:00:00-07:00\n- Resolve tomorrow -> 2026-08-25, 6:40 AM -> 06:40 (explicit AM); delta = 940 minutes -> departure_time = 2026-08-25T06:40:00-07:00; stations Gilroy and San Jose Diridon both valid; then finish.\n\nC) question: "How do I get from Fremont to Sunnyvale?" reference_datetime: 2026-08-24T15:00:00-07:00\n- Fremont is not a Caltrain station -> departure_station = null; arrival_station = Sunnyvale; no time stated -> departure_time = null; finish immediately, no calculation needed.'
    question = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Question:', 'desc': '${question}'})
    reference_datetime = Field(annotation=str required=True json_schema_extra={'desc': 'Current date and time in the America/Los_Angeles timezone formatted as ISO 8601', '__dspy_field_type': 'input', 'prefix': 'Reference Datetime:'})
    trajectory = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Trajectory:', 'desc': '${trajectory}'})
    next_thought = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Thought:', 'desc': '${next_thought}'})
    next_tool_name = Field(annotation=Literal['datetime_calculator', 'finish'] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Tool Name:', 'desc': '${next_tool_name}'})
    next_tool_args = Field(annotation=dict[str, Any] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Tool Args:', 'desc': '${next_tool_args}'})
))
extract.predict = Predict(StringSignature(question, reference_datetime, trajectory -> reasoning, departure_station, arrival_station, departure_time
    instructions='Extract a Caltrain route (departure station, arrival station) and an optional departure time from the question.\n\n## Inputs\n- **question**: a natural-language request describing a trip between two Caltrain stations, possibly with a date/time.\n- **reference_datetime**: the current date/time in ISO 8601 format with timezone offset (e.g., 2026-08-24T15:00:00-07:00). Use it to resolve all relative date/time expressions.\n\n## Outputs\n- **reasoning**: a brief explanation of how the stations and departure time were derived, including the day-of-week determination for any weekday expressions.\n- **departure_station**: the origin station, or null if it cannot be resolved from the question.\n- **arrival_station**: the destination station, or null if it cannot be resolved from the question.\n- **departure_time**: the departure time in ISO 8601 format (YYYY-MM-DDTHH:MM:SS±HH:MM) using the same timezone offset as the reference_datetime, or null if the question does not specify a departure time.\n\n## Station resolution rules\n- The origin follows phrasing like "from X"; the destination follows phrasing like "to Y" or "reach Y".\n- If only a destination is given (e.g., "Get me to 22nd Street at 8 PM"), set departure_station to null. Do not invent an origin.\n- Output station names as lowercase plain-text strings with NO surrounding quotation marks (e.g., `san francisco`, `22nd street`, `palo alto`, `south san francisco`, `bayshore`, `morgan hill`). Never output values like `\'south san francisco\'` with embedded quotes.\n- Keep the station name as stated in the question, lowercased. For example, "San Jose Diridon" refers to the San Jose (Diridon) station; output it as `san jose diridon`.\n- Caltrain stations (north to south) include: San Francisco, 22nd Street, Bayshore, South San Francisco, San Bruno, Millbrae, Burlingame, San Mateo, Hayward Park, Hillsdale, Belmont, San Carlos, Redwood City, Menlo Park, Palo Alto, California Avenue, San Antonio, Mountain View, Sunnyvale, Lawrence, Santa Clara, San Jose (Diridon), Tamien, Capitol, Blossom Hill, Morgan Hill, San Martin, Gilroy. Return null for any station that cannot be resolved from the question.\n\n## Departure time rules\n- Return null when the question does not specify any time.\n- When the question specifies a time, treat it as the DEPARTURE time exactly as stated. Never interpret a stated time as an arrival time and never subtract an estimated travel duration to back-calculate a departure time. For example, "reach Bayshore from South San Francisco early tomorrow, 5:30 AM" means departure_time = 5:30 AM tomorrow, NOT 5:00 AM.\n- Preserve the exact stated time; do not round or approximate (7:05 AM stays 07:05, not 07:00).\n\n### AM/PM → 24-hour conversion (do this carefully; errors here are common)\n- 12:00 AM–12:59 AM → 00:00–00:59 (e.g., 12:05 AM = 00:05, i.e., just after midnight at the START of the stated date).\n- 1 AM–11:59 AM → 01–11 (unchanged hour).\n- 12:00 PM–12:59 PM → 12:00–12:59 (noon).\n- 1 PM–11:59 PM → add 12 (e.g., 5:30 PM = 17:30, 8 PM = 20:00 — NOT 16:00).\n\n### Date resolution\n- No date given, only a time of day: use the calendar date of reference_datetime (e.g., reference 2026-08-24T15:00:00-07:00 + "8 PM" → 2026-08-24T20:00:00-07:00). If the stated time has already passed on the reference date, use the following day.\n- "tomorrow" = the calendar day after the reference date.\n- "X hours/minutes from now" = reference_datetime + X.\n- Explicit dates (e.g., "August 25", "this Thursday, August 27") = that calendar date; combine with the stated time of day. If no year is given, use the year of the reference_datetime.\n- "this <weekday>" = the named weekday in the week containing the reference date (the upcoming one, later in the same week). You MUST first determine the day of week of the reference date — do not guess it.\n\n### Determining the day of week (critical — a wrong weekday was the cause of a failed example)\n- Compute it from a known anchor and count days modulo 7. Reliable anchors: 2026-01-01 is a Thursday; 2026-08-24 is a MONDAY.\n- For reference, the week of 2026-08-24 is: Mon Aug 24, Tue Aug 25, Wed Aug 26, Thu Aug 27, Fri Aug 28, Sat Aug 29, Sun Aug 30.\n- Therefore, with reference 2026-08-24 (Monday), "this Friday" = 2026-08-28 (NOT 2026-08-29, which is a Saturday). Note 2026-08-24 is NOT a Thursday.\n- Sanity check: after picking a date, verify that the date you chose actually falls on the stated weekday. If an explicit date is given along with a weekday (e.g., "Thursday, August 27"), the two should agree — August 27, 2026 is indeed a Thursday.\n\n## Tool use\n- You may use the datetime_calculator tool with arguments {"start_time": ..., "delta_minutes": ...} ONLY for relative-time arithmetic anchored at the reference_datetime (e.g., adding 120 minutes for "two hours from now"). Do NOT use it to subtract assumed travel times between stations, and do not use it in a way that alters an explicitly stated time.\n- Explicitly stated dates/times need NO tool at all: construct the ISO string directly from (resolved calendar date) + (converted 24-hour time) + (reference timezone offset). Computing "minutes from the reference to an explicit target time" is error-prone and unnecessary — avoid it.\n- If you do use the tool, ALWAYS sanity-check its output against your own arithmetic. Tool observations can be inconsistent with the inputs. If the tool result contradicts a directly computed explicit date/time, trust the direct computation (e.g., 12:05 AM on August 25 is unambiguously 2026-08-25T00:05:00-07:00 regardless of any tool output). Conversely, if your manual delta/date math and the tool disagree, recheck your manual date and weekday reasoning before finalizing.\n\n## Final verification checklist\n1. Station names lowercased, no quotes; null for any unresolvable/missing station.\n2. AM/PM converted correctly (12 AM → 00, 8 PM → 20:00).\n3. Weekday of the reference date computed (not assumed); the chosen date actually falls on the stated weekday.\n4. Stated time preserved exactly; timezone offset matches reference_datetime.\n\n## Worked examples\n- question: "Two hours from now, get me from San Francisco to Palo Alto." reference_datetime: 2026-08-24T15:00:00-07:00\n  → departure_station: san francisco; arrival_station: palo alto; departure_time: 2026-08-24T17:00:00-07:00\n- question: "I need to reach Bayshore from South San Francisco early tomorrow, 5:30 AM." reference_datetime: 2026-08-24T15:00:00-07:00\n  → departure_station: south san francisco; arrival_station: bayshore; departure_time: 2026-08-25T05:30:00-07:00\n- question: "This Thursday, August 27, at 7:05 AM: Morgan Hill to San Francisco." reference_datetime: 2026-08-24T15:00:00-07:00\n  → departure_station: morgan hill; arrival_station: san francisco; departure_time: 2026-08-27T07:05:00-07:00\n- question: "Show trains from San Jose Diridon to Tamien at 12:05 AM on August 25." reference_datetime: 2026-08-24T15:00:00-07:00\n  → departure_station: san jose diridon; arrival_station: tamien; departure_time: 2026-08-25T00:05:00-07:00 (12:05 AM = 00:05 at the start of Aug 25; direct formatting, no delta math needed)\n- question: "Get me to 22nd Street at 8 PM." reference_datetime: 2026-08-24T15:00:00-07:00\n  → departure_station: null; arrival_station: 22nd street; departure_time: 2026-08-24T20:00:00-07:00 (no origin stated; 8 PM = 20:00 on the reference date)\n- question: "This Friday at 5:30 PM, take me from Belmont to San Carlos." reference_datetime: 2026-08-24T15:00:00-07:00\n  → 2026-08-24 is a Monday, so this Friday is 2026-08-28 (verify: Aug 28, 2026 is a Friday); 5:30 PM = 17:30\n  → departure_station: belmont; arrival_station: san carlos; departure_time: 2026-08-28T17:30:00-07:00'
    question = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Question:', 'desc': '${question}'})
    reference_datetime = Field(annotation=str required=True json_schema_extra={'desc': 'Current date and time in the America/Los_Angeles timezone formatted as ISO 8601', '__dspy_field_type': 'input', 'prefix': 'Reference Datetime:'})
    trajectory = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Trajectory:', 'desc': '${trajectory}'})
    reasoning = Field(annotation=str required=True json_schema_extra={'prefix': "Reasoning: Let's think step by step in order to", 'desc': '${reasoning}', '__dspy_field_type': 'output'})
    departure_station = Field(annotation=Union[str, NoneType] required=True json_schema_extra={'desc': 'Canonical departure station from: 22nd street, bayshore, belmont, blossom hill, broadway, burlingame, california avenue, capitol, college park, gilroy, hayward park, hillsdale, lawrence, menlo park, millbrae, morgan hill, mountain view, palo alto, redwood city, san antonio, san bruno, san carlos, san francisco, san jose diridon, san martin, san mateo, santa clara, south san francisco, sunnyvale, tamien; null if missing', '__dspy_field_type': 'output', 'prefix': 'Departure Station:'})
    arrival_station = Field(annotation=Union[str, NoneType] required=True json_schema_extra={'desc': 'Canonical arrival station from: 22nd street, bayshore, belmont, blossom hill, broadway, burlingame, california avenue, capitol, college park, gilroy, hayward park, hillsdale, lawrence, menlo park, millbrae, morgan hill, mountain view, palo alto, redwood city, san antonio, san bruno, san carlos, san francisco, san jose diridon, san martin, san mateo, santa clara, south san francisco, sunnyvale, tamien; null if missing', '__dspy_field_type': 'output', 'prefix': 'Arrival Station:'})
    departure_time = Field(annotation=Union[datetime, str, NoneType] required=True json_schema_extra={'desc': 'Approximate departure time as an ISO 8601 datetime; null when the question omits a time', '__dspy_field_type': 'output', 'prefix': 'Departure Time:'})
))

# Re-Evaluate Merged Set

In [54]:
lm = dspy.LM(
    model="openrouter/ibm-granite/granite-4.1-8b",
    api_base="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)
dspy.configure(lm=lm)

In [55]:
evaluator = dspy.Evaluate(
    devset=trainset + valset,
    num_threads=10,
    display_progress=True,
    display_table=5,
    provide_traceback=False,
    max_errors=5,
    failure_score=0.0,
)

In [56]:
prog_gepa_optimized_merged_set_result = evaluator(gepa_prog, metric=baseline_metric)

Average Metric: 143.67 / 179 (80.3%): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 179/179 [01:40<00:00,  1.78it/s]

2026/08/25 16:30:19 INFO dspy.evaluate.evaluate: Average Metric: 143.6666666666667 / 179 (80.3%)

,id,family_id,scenario,question,reference_datetime,is_schedule_question,departure_station,arrival_station,departure_time,time_tolerance_minutes,prediction,baseline_metric
0,train-001,train-now-001,schedule_now_alias,Next Caltrain from Sunnyvale to SF?,2026-08-24T15:00:00-07:00,True,sunnyvale,san francisco,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='sunnyvale', arrival_station='s...",✔️ [0.667]
1,train-002,train-now-002,schedule_now_reversed_alias,I need to get to 4th and King from Palo Alto. What's the next one?,2026-08-24T15:00:00-07:00,True,palo alto,san francisco,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='palo alto', arrival_station='s...",✔️ [1.000]
2,train-003,train-now-003,schedule_now_alias,Catching the next train at Diridon going to Mountain View.,2026-08-24T15:00:00-07:00,True,san jose diridon,mountain view,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='san jose diridon', arrival_sta...",✔️ [1.000]
3,train-004,train-now-004,schedule_now,Any train leaving Redwood City for Millbrae right now?,2026-08-24T15:00:00-07:00,True,redwood city,millbrae,2026-08-24T15:00:00-07:00,5.0,"ScheduleQuestion(departure_station='redwood city', arrival_station...",✔️ [1.000]
4,train-005,train-now-005,schedule_now_alias,"ASAP, 22nd St to San Mateo - what can I catch?",2026-08-24T15:00:00-07:00,True,22nd street,san mateo,2026-08-24T15:00:00-07:00,5.0,UnsupportedQuestion(),✔️ [0.000]

In [57]:
prog_gepa_optimized_merged_set_result.score

80.26